---
- hosts: db_hosts
  become: true

  tasks:
  - name: Check if database is standing by
    stat:
      path: '/var/lib/postgresql/12/main/standby.signal'
    register: standby_status
  - name: Check if database is standing by
    stat:
      path: '/var/lib/postgresql/12/main/standby.signal'
    register: standby_status
  roles:
    - base

- hosts: db_master
  become: true
  roles:
    - master

- hosts: db_slaves
  become: true
  roles:
    - slave
