---

- name: "Install tools and PostgreSQL 12"
  package:
    name:
    - wget
    - nano
    - net-tools
    - postgresql
    - postgresql-12
    - python3-psycopg2
    state: present
    update_cache: true

- name: "Enable PostgreSQL service on boot"
  systemd:
    name: postgresql
    state: started
    enabled: yes
